version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file: .env
    networks:
      - app-network
    volumes:
      - pg_data:/var/lib/postgresql/data



volumes:
  pg_data:
    driver: local


networks:
  app-network:
    driver: bridge
  kafka-network:
    driver: bridge
